In [1]:
import sys
sys.path.append('../Scripts')

# # for reading datafiles 
import pandas as pd
# import script that has many standard functions:
from PostProcessingScripts import * 

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))


obtain index of the SFRD models that we want to highlight


In [2]:
#Needed in general
import numpy as np
import matplotlib.pyplot as plt
import sys

#Quick fudge to make import from ../Scripts work
sys.path.append('../../Scripts')

#Custom imports
import ClassCOMPAS     as CC ###
import ClassFormationChannels as FC 
# import coencodeVarious        as CV


In [3]:
#all the counts strings and channels are sorted
#this function prints the main channels and checks what 
#percentage of all DCO=type is accounted for
def printTopXchannels(x):
    maxx = x
    i    = 0
    totalPercentage = 0.
    while i <= maxx:
        print( 'Nr systems = %s'%(fc.sortedCounts[i]))
        percentage = fc.sortedCounts[i] / float(np.sum(fc.sortedCounts))
        print( 'pecentage of all %s' %(percentage))
        totalPercentage += percentage
        print(fc.sortedStrings[i])
        i +=1
        print( 'ssss ', len(fc.sortedCounts))
    print('the above channels account for %s of all systems'  )
    %(totalPercentage)
    
    
    
    

In [4]:
BPSmodelName ='A'
DCOtype='BBH'

path_ = '/Volumes/Andromeda2/DATA/AllDCO_bugfix/' + alphabetDirDict[BPSmodelName] +'/'
path  = path_ + 'COMPASCompactOutput_'+ DCOtype +'_' + BPSmodelName + '.h5'

#hdf5 name needs to be: COMPASOutput.h5

#If you want to see what steps and class attributes are set -> verbose=True
fc = FC.FormationChannels(path = path,verbose=True)

In [5]:
#I dont want to take the merged within Hubble time into account in the formation
#channels. meaning if we have two exactly the same channels but one mergers within 
#Hubble and one doesnt. Techinally this is two different channels.
#By adding this column to delete columns we ignore this colum.
#Same could be done for stellar types of donors etc
# fc.deleteColumns = ['merged_in_Hubble_time'] #/floor

# For DCO types I have inbuilt sorter to return seeds
# set types argument and leave seeds argument empty (or None)
#note that withinHubbleTime and optimistic argument are  only used
# when types is given, not for seeds.
#Additionally there are the following arguments with their Default:
#   withinHubbleTime=True, optimistic=False
#Not that optimistic True, or withinHubble = False does not give opposite but all systems
fc.formationChannelsSeeds(seeds=None, types='BBH', withinHubbleTime=True, optimistic=True)


self.booleanFilter 
 Looking up the seeds/systems and creating mask for formation Channels. 
Doing the formation channels for 8371398 systems
self.header 
 Sorted which columns from formation channels we use
Counting/sorting the unique Channels
self.sortedChannels self.sortedCounts 
 Combining the counts and channels in arrays
120250.46419909708 sum sorted counts
Done
self.rankArray 
 Creating column with rank of each system, patience required :)
Done :D 
self.sortedSeeds 
 Creating array per channel with all seeds of that channel
self.sortedStrings 
 Constructing human readable string for each of the unique Channels (Magic) 
 :D :D 
 finished in total we have 150 channels for 120250.46419909708 systems


In [6]:


Data            = CC.COMPASData(path=path, lazyData=True, Mlower=5., \
                 Mupper=150., binaryFraction=0.6)
# print len(Data.mass1[...].squeeze())
#     print(len(Data.mass1))
Data.setCOMPASDCOmask(types='BBH',  withinHubbleTime=True, optimistic=False)
Data.setCOMPASData()
if len(Data.mass1[...].squeeze()):
    print(len(Data.mass1))

SeedsHubble    = Data.seeds[Data.Hubble==True]
print(len(SeedsHubble))

weighted samples :-D
Remember to  self.setCOMPASDCOmask() and self.setCOMPASData()
8371398
8371398


In [15]:
#The method :
#Go index by index -> read string and group in cell below the indices
#Note some channels do exactlu the #same but one is within Hubble other not, 
#this is classified as differencce
for index in range(10):#[1] #[13,18,26,30,36,40,41,45,46,48]  #[9,10,14,31,34,44] #,18,26,30,36,40,41,45,46,48] #,10,14,31,34,44]
    index = index-1+1
    print( fc.sortedStrings[index])

    print( 'I have now accounted for  %s percent', np.sum(fc.sortedCounts[0:index+1])*100 / float(np.sum(fc.sortedCounts)))


    seedsInterest = []
    seedsInterest.extend(fc.sortedSeeds[index])
    #         Get metallicity systems this works because seeds in both
    #         files are in the same order
    mask = np.in1d(Data.seeds, np.array(seedsInterest))
    mass1 = Data.mass1[mask]
    mass2 = Data.mass2[mask]
    print(mass1)
    print(len(seedsInterest))

# print(len(mass1))

 ->mt_primary_ep1 P=HG  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=CHeB  ->CEE ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=CHeB  -> merged within Hubble=True -> binary disrupted=False
I have now accounted for  %s percent 35.800815422427505
[17.0417  16.8936  21.6115  ...  5.31236  4.05417  4.28648]
3430176
 ->mt_primary_ep1 P=HG  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=HG  ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=HG  -> merged within Hubble=True -> binary disrupted=False
I have now accounted for  %s percent 55.81292700845311
[14.5644  15.1474  18.7321  ...  7.45536  7.23138  7.15963]
1851262
 ->mt_primary_ep1 P=CHeB  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=CHeB  ->CEE ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=CHeB  -> merged within Hubble=True -> binary disrupted=False
I have now accounted for  %s percent 70.35326212138796
[15.8194  17.0057  15.

## Model B 

In [16]:
BPSmodelName ='B'
DCOtype='BBH'

path_ = '/Volumes/Andromeda2/DATA/AllDCO_bugfix/' + alphabetDirDict[BPSmodelName] +'/'
path  = path_ + 'COMPASCompactOutput_'+ DCOtype +'_' + BPSmodelName + '.h5'

#hdf5 name needs to be: COMPASOutput.h5

#If you want to see what steps and class attributes are set -> verbose=True
fc = FC.FormationChannels(path = path,verbose=True)

#I dont want to take the merged within Hubble time into account in the formation
#channels. meaning if we have two exactly the same channels but one mergers within 
#Hubble and one doesnt. Techinally this is two different channels.
#By adding this column to delete columns we ignore this colum.
#Same could be done for stellar types of donors etc
# fc.deleteColumns = ['merged_in_Hubble_time'] #/floor

# For DCO types I have inbuilt sorter to return seeds
# set types argument and leave seeds argument empty (or None)
#note that withinHubbleTime and optimistic argument are  only used
# when types is given, not for seeds.
#Additionally there are the following arguments with their Default:
#   withinHubbleTime=True, optimistic=False
#Not that optimistic True, or withinHubble = False does not give opposite but all systems
fc.formationChannelsSeeds(seeds=None, types='BBH', withinHubbleTime=True, optimistic=True)



Data            = CC.COMPASData(path=path, lazyData=True, Mlower=5., \
                 Mupper=150., binaryFraction=0.6)
# print len(Data.mass1[...].squeeze())
#     print(len(Data.mass1))
Data.setCOMPASDCOmask(types='BBH',  withinHubbleTime=True, optimistic=False)
Data.setCOMPASData()
if len(Data.mass1[...].squeeze()):
    print(len(Data.mass1))

SeedsHubble    = Data.seeds[Data.Hubble==True]
print(len(SeedsHubble))


#The method :
#Go index by index -> read string and group in cell below the indices
#Note some channels do exactlu the #same but one is within Hubble other not, 
#this is classified as differencce
for index in range(10):#[1] #[13,18,26,30,36,40,41,45,46,48]  #[9,10,14,31,34,44] #,18,26,30,36,40,41,45,46,48] #,10,14,31,34,44]
    index = index-1+1
    print( fc.sortedStrings[index])

    print( 'I have now accounted for  %s percent', np.sum(fc.sortedCounts[0:index+1])*100 / float(np.sum(fc.sortedCounts)))


    seedsInterest = []
    seedsInterest.extend(fc.sortedSeeds[index])
    #         Get metallicity systems this works because seeds in both
    #         files are in the same order
    mask = np.in1d(Data.seeds, np.array(seedsInterest))
    mass1 = Data.mass1[mask]
    mass2 = Data.mass2[mask]
    print(mass1)
    print(len(seedsInterest))

# print(len(mass1))

self.booleanFilter 
 Looking up the seeds/systems and creating mask for formation Channels. 
Doing the formation channels for 8616008 systems
self.header 
 Sorted which columns from formation channels we use
Counting/sorting the unique Channels
self.sortedChannels self.sortedCounts 
 Combining the counts and channels in arrays
129333.9378383593 sum sorted counts
Done
self.rankArray 
 Creating column with rank of each system, patience required :)
Done :D 
self.sortedSeeds 
 Creating array per channel with all seeds of that channel
self.sortedStrings 
 Constructing human readable string for each of the unique Channels (Magic) 
 :D :D 
 finished in total we have 147 channels for 129333.9378383593 systems
weighted samples :-D
Remember to  self.setCOMPASDCOmask() and self.setCOMPASData()
8616008
8616008
 ->mt_primary_ep1 P=HG  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=CHeB  ->CEE ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=CHeB  -> merged within 

In [17]:


# read in data 
fdata = h5.File(path, 'r')


# # set optimistic true if that is the variation (H) 
# OPTIMISTIC=False
# if (BPSmodelName=='F') | (BPSmodelName=='K') :
#     OPTIMISTIC=True 

# obtain DCO masses
M1 = fdata['doubleCompactObjects']['M1'][...].squeeze()
M2 = fdata['doubleCompactObjects']['M2'][...].squeeze()
MBH, MNS = obtainM1BHandM2BHassymetric(M1, M2)

whichSN = fdata['supernovae']['whichStar'][...].squeeze() 

DCOseeds = fdata['doubleCompactObjects']['seed'][...].squeeze()
seedsSN = fdata['supernovae']['randomSeed'][...].squeeze()

u, indices = np.unique(seedsSN, return_index=True)
whichSN = fdata['supernovae']['whichStar'][...].squeeze()[indices] # get whichStar for first SN 

mask_temp = ((whichSN==2) & (M1>M2) )
mask_2 = ((whichSN==1) & (M1<M2))
print('nr of weird reversals = %s'%np.sum(mask_temp))
print('nr of normal reversals = %s'%np.sum(mask_2))


nr of weird reversals = 4826
nr of normal reversals = 1254877


In [19]:
from formation_channels import * 

In [20]:
maskMRR = ((whichSN==2) & (M1>M2) ) | ((whichSN==1) & (M1<M2) ) 





# get intrinsic weights
fparam_intrinsic = 'weights_intrinsic'
# get detected weights
fparam_detected = 'weights_detected'


####################################################
######### ITERATE  OVER  MSSFR  MODELS #############
####################################################

fdata = h5.File(path)

# DCOSeeds = fdata['doubleCompactObjects']['seed'][...].squeeze()
seeds = fdata['doubleCompactObjects']['seed'][...].squeeze()
channels = identify_formation_channels(seeds=seeds, file=fdata)
# headerDict_intrinsic = { 5:'MRR Channel VI intrinsic (z=0) [Gpc^{-3} yr^{-1}]',  6:'MRR Channel VII intrinsic (z=0) [Gpc^{-3} yr^{-1}]', 7:'All intrinsic (z=0) [Gpc^{-3} yr^{-1}]', 8:'All MRR intrinsic (z=0) [Gpc^{-3} yr^{-1}]', 0:'MRR channel V intrinsic (z=0) [Gpc^{-3} yr^{-1}]',  1:'MRR channel I intrinsic (z=0) [Gpc^{-3} yr^{-1}]', 2:'MRR channel II intrinsic (z=0) [Gpc^{-3} yr^{-1}]',3:'MRR channel III intrinsic (z=0) [Gpc^{-3} yr^{-1}]', 4:'MRR channel IV intrinsic (z=0) [Gpc^{-3} yr^{-1}]'}
# headerDict_observed  = { 5:'MRR channel VI observed (design LVK) [yr^{-1}]',     6:'MRR channel VII observed (design LVK) [yr^{-1}]',    7:'All observed (design LVK) [yr^{-1}]',    8:'All MRR observed (design LVK) [yr^{-1}]', 0:'MRR channel V observed (design LVK) [yr^{-1}]', 1:'MRR channel I observed (design LVK) [yr^{-1}]', 2:'MRR channel II observed (design LVK) [yr^{-1}]', 3:'MRR channel III observed (design LVK) [yr^{-1}]', 4:'MRR channel IV observed (design LVK) [yr^{-1}]'}    
# enumerate_list = range(9)




In [37]:
Channel = 0  
mask_C  = (channels==Channel) & (maskMRR==1)


intrinsicRates = np.zeros(len(MSSFRnameslist))
detectedRates = np.zeros(len(MSSFRnameslist))       


for ind_mssfr, mssfr in enumerate([MSSFRnameslist[0]]):
    weightheader = 'w_' + mssfr
    w_int = fdata[fparam_intrinsic][weightheader][...].squeeze()
    w_det = fdata[fparam_detected][weightheader][...].squeeze()




print(Data.seeds[mask_C])
norm_det = np.sum(w_det[maskMRR])
AA = np.sum(w_det[mask_C])/norm_det
print(AA)

[   5001039    5003491    5004064 ... 3960011771 3960020783 4065018882]
0.6707928963246164


In [41]:
#The method :
#Go index by index -> read string and group in cell below the indices
#Note some channels do exactlu the #same but one is within Hubble other not, 
#this is classified as differencce
for index in range(10):#[1] #[13,18,26,30,36,40,41,45,46,48]  #[9,10,14,31,34,44] #,18,26,30,36,40,41,45,46,48] #,10,14,31,34,44]
    print(' ---- now at index ---- ', index)
    index = index-1+1

    seedsInterest = []
    seedsInterest.extend(fc.sortedSeeds[index])
    #         Get metallicity systems this works because seeds in both
    #         files are in the same order
    mask = np.in1d(Data.seeds[mask_C], np.array(seedsInterest))
    mass1 = Data.mass1[mask_C][mask]
    mass2 = Data.mass2[mask_C][mask]

    
    if len(mass1>1):
        print(mass1)
          
        print(len(seedsInterest))

        print( fc.sortedStrings[index])

        print( 'I have now accounted for  %s percent', np.sum(fc.sortedCounts[0:index+1])*100 / float(np.sum(fc.sortedCounts)))
        print('this channel accounts for a fraction of  ', np.sum(w_det[mask_C][mask])/np.sum(w_det[mask_C]), ' of the other MRR BBHs channel' )
        print()
        print()


 ---- now at index ----  0
 ---- now at index ----  1
 ---- now at index ----  2
[22.5077 19.9356 22.4711 ... 11.0437 11.4199 11.4354]
145512
 ->mt_primary_ep1 P=MS  S=MS  ->mt_primary_ep2 P=HG  S=MS  ->ccSN primary  ->mt_secondary_ep1 P=BH  S=HG  ->ccSN secondary  -> last type Primary in Form=BH  -> last type Secondary in Form=HG  -> merged within Hubble=True -> binary disrupted=False
I have now accounted for  %s percent 76.08887837517732
this channel accounts for a fraction of   0.6964447676581794  of the other MRR BBHs channel


 ---- now at index ----  3
 ---- now at index ----  4
 ---- now at index ----  5
 ---- now at index ----  6
[ 6.86769  9.92617 12.3416  ...  2.71364  2.69237  2.80826]
89129
 ->mt_primary_ep1 P=CHeB  S=CHeB  ->mt_secondary_ep1 P=HeMS  S=CHeB  ->CEE ->ccSN primary  ->ccSN secondary  -> last type Primary in Form=HeMS  -> last type Secondary in Form=CHeB  -> merged within Hubble=True -> binary disrupted=False
I have now accounted for  %s percent 88.695138730690

In [44]:
print( fdata['commonEnvelopes']['randomSeed'].keys())

<KeysViewHDF5 ['EccentricityPostCEE', 'EccentricityPreCEE', 'MSAccretorDuringCEEFlag', 'SemiMajorAxisPostCEE', 'SemiMajorAxisPreCEE', 'Teff1', 'Teff2', 'alphaCE', 'bEFixed1', 'bEFixed2', 'bEKruckow1', 'bEKruckow2', 'bELoveridge1', 'bELoveridge2', 'bELoveridgeWinds1', 'bELoveridgeWinds2', 'bENanjing1', 'bENanjing2', 'bindingEnergy1', 'bindingEnergy2', 'counterCEE', 'doubleCoreCommonEnvelopeFlag', 'finalStellarType1', 'finalStellarType2', 'flagRLOF1', 'flagRLOF2', 'immediateRLOFAfterCEE', 'lambda1', 'lambda2', 'lambdaFixed1', 'lambdaFixed2', 'lambdaKruckow1', 'lambdaKruckow2', 'lambdaLoveridge1', 'lambdaLoveridge2', 'lambdaLoveridgeWinds1', 'lambdaLoveridgeWinds2', 'lambdaNanjing1', 'lambdaNanjing2', 'luminosity1', 'luminosity2', 'm_EccentricityRLOF', 'mass1', 'mass1ZAMS', 'mass2', 'mass2ZAMS', 'massCore1', 'massCore2', 'massEnvelope1', 'massEnvelope2', 'massTransferTrackerHistory', 'optimisticCommonEnvelopeFlag', 'radius1', 'radius1AfterStripping', 'radius2', 'radius2AfterStripping', 'r